default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  # password: password
  host: db

development:
  <<: *default
  database: app_name_development
  host: db

test:
  <<: *default
  database: app_name_test
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  socket: /tmp/mysql.sock

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: weinance_db
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>